CC = gcc
CFLAGS = -std=c99 -g -Wall -Wextra -Wpedantic

all:
	$(CC) $(CFLAGS) -o problem41 problem4a.c
	$(CC) $(CFLAGS) -o problem43 problem4c.c

test:
		./problem43 input.txt

clean:
	rm -f problem4a
	rm -f problem4c
