CC = gcc
CFLAGS = -std=c99 -g -Wall -Wextra -Wpedantic

all: problem4a problem4b problem4c

	$(CC) $(CFLAGS) -o problem41 problem4a.c
	$(CC) $(CFLAGS) -o problem42 problem4b.c
	$(CC) $(CFLAGS) -o problem43 problem4c.c


clean:
	rm -f problem4a
	rm -f problem4c
